# Orda CPU makefile
#
# author: Igor Lesik
# copyright: Igor Lesik 2017

# All = installation
#.PHONY: all
#all: installation


# Path to build files sources.
SRC_BLD := $(SOURCE_PATH)/bld


# Include other makefiles
include $(SRC_BLD)/path.makefile
include $(SRC_BLD)/scala.rules.makefile
include $(SRC_BLD)/scala.dv.makefile
include $(SRC_BLD)/doc.makefile
include $(SRC_BLD)/install.makefile
