# Orda CPU makefile
#
# author: Igor Lesik
# copyright: Igor Lesik 2017

# All = installation
#.PHONY: all
#all: installation

#EMPTY :=
#SPACE := $(EMPTY) $(EMPTY)

# Path where applications are installed.
INSTALL_PATH := $(abspath ./install)

# Path to build files
BLD := $(SOURCE_PATH)/bld

# Scala version
#SCALA_MAJOR_VER := $(shell $(SCALAC) -version 2>&1 | cut -d ' ' -f 4 | cut -d '.' -f 1,2)
#$(info Using Scala major release $(SCALA_MAJOR_VER))

# Include other makefiles
include $(BLD)/doc.makefile

